package modelo;
// Generated 20/03/2018 02:44:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private int idpregunta;
     private Usuario usuario;
     private String contenido;
     private Set respuestas = new HashSet(0);

    public Pregunta() {
    }

	
    public Pregunta(int idpregunta, Usuario usuario, String contenido) {
        this.idpregunta = idpregunta;
        this.usuario = usuario;
        this.contenido = contenido;
    }
    public Pregunta(int idpregunta, Usuario usuario, String contenido, Set respuestas) {
       this.idpregunta = idpregunta;
       this.usuario = usuario;
       this.contenido = contenido;
       this.respuestas = respuestas;
    }
   
    public int getIdpregunta() {
        return this.idpregunta;
    }
    
    public void setIdpregunta(int idpregunta) {
        this.idpregunta = idpregunta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public Set getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set respuestas) {
        this.respuestas = respuestas;
    }




}


